title: Ticketmaster Innovation
url: https://tm-innovation.github.io
logo: /assets/images/tm-innovation-logo.png

gtm-container-id: 'GTM-K4QMLG' # Google Tag Manager

collections:
  products:
    output: true

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/innovation-open.jpg
  - scope:
      path: ""
      type: products
    values:
      layout: product

exclude:
  - bower_components
  - node_modules
  - js
  - scss
  - bower.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

plugins:
  - jekyll-seo-tag
